name: deploy CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

  deploy:
    runs-on: ubuntu-latest
    
    needs: test

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
      
      - name: vercel pull
        run: vercel pull --yes --environment=production --token=${{ secrets.GH_ACTIONS_VERCEL_TOKEN }}

      - name: build project
        run: vercel build --prod --token=${{ secrets.GH_ACTIONS_VERCEL_TOKEN }}

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.GH_ACTIONS_VERCEL_TOKEN }}
          VERCEL_ORG_ID: 67rdqStzHuCt5XHpBAkI4D3z
          VERCEL_PROJECT_ID: prj_H196ekz6YOalgeVLl5j9ket3xwY0
          PREBUILT: true
          PRODUCTION: true
